# Generated by Django 4.0.6 on 2022-07-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacasPatentes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('patente', models.CharField(max_length=7, unique=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
